### ISSUE TITLE
ImportError: cannot import name 'ddpm' from 'models'

### ISSUE THREAD

**Issue by landiaokafeiyan** [Newbeeer/Poisson_flow#1]

**Comment by Newbeeer** [comment]
Hi Liangyan,

Thanks for pointing out the issue! We mistakenly deleted the DDPM files in the repo before. We didn't use DDPM model in current implementation, so I remove its reference in `run_lib.py` file. Please use the updated version!

Please let me know if the problem persists, or there are any follow-up issues.

Thanks,
Yilun

**Comment by landiaokafeiyan** [comment]
Hi Yilun,

Thank you for the update. 

I am trying to understand your paper with the code,  any details will be very helpful.

Appreciate your reply.

Liangyan

**Comment by Newbeeer** [comment]
Sure. Feel free to open an issue anytime! Thanks.
