### ISSUE TITLE
Request for a Talk on Poisson Flow Generative Models

### ISSUE THREAD

**Issue by huanranchen** [Newbeeer/Poisson_flow#14]
Hello!

I'm extremely interested in Poisson Flow Generative Models (PFGM) and their improved versions. I would love to gain insights into the thought process behind designing such models. I was wondering if there are any plans to give a talk on PFGMs in the near future?

best wishes

**Comment by Newbeeer** [comment]
Hi,

Thanks for the request. Could we discuss the this privately? My email: ylxu@mit.edu; my WeChat: aaronyilun

Best,
Yilun
