### ISSUE TITLE
Could not find a version that satisfies the requirement absl==0.0

### ISSUE THREAD

**Issue by Maurdekye** [Newbeeer/Poisson_flow#3]
I created a new conda environment in wsl2 in order to set up the repo, but I get this error when I attempt to install requirements.txt. I see that absl_py==1.2.0 is already a requirement; is this extra requirement a mistake?

**Comment by Newbeeer** [comment]
Hi,

Thanks for pointing out the issue! I generated the requirement files by `pipreqs` and didn't double check the file. I've removed the absl==0.0 line in the file.

Yilun
