### ISSUE TITLE
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.10; Detected an installation of version 2.9.0. Please upgrade TensorFlow to proceed.

### ISSUE THREAD

**Issue by reflectionie** [Newbeeer/Poisson_flow#6]
Hi, I made sure I used python3.9.2 as you do and installed the package with requirements.txt, but I still have this error, if I update tensorflow it will raise other errors; May I ask why?

**Comment by reflectionie** [comment]
Also, according to the requirements.txt, I need to install jax==0.3.16, and it will install scipy 1.9.2, but the version of scipy in the requirements.txt is 1.7.3. Could you please tell me what I should do

**Comment by reflectionie** [comment]
My environment is cuda11.6, RTX2080TI

**Comment by Newbeeer** [comment]
Hi,

I generate the requirement.txt by `pipreqs` command. It may omit the dependency between packages, and instead faithfully list them. 

I locally used `tensorflow-probability==0.17.0` with `tensorflow==2.9.0`. I guess a higher version of `tensorflow-probability` causes the conflict. I've added the line to requirement.text

Thanks for pointing out the inconsistency on `scipy`. I think both versions work fine (locally I used 1.7.3). I've deleted the `scipy` line in requirements, leaving it to the users. 

Please let me know if the problems persist!

Thanks,
Yilun

**Comment by reflectionie** [comment]
Thank you for the update! this error is not thrown now
