### ISSUE TITLE
upfirdn2d_op = load(     "upfirdn2d",     sources=[         os.path.join(module_path, "upfirdn2d.cpp"),         os.path.join(module_path, "upfirdn2d_kernel.cu"),     ], )

### ISSUE THREAD

**Issue by reflectionie** [Newbeeer/Poisson_flow#7]
Hi, when I run "python3 main.py --config ./configs/poisson/cifar10_ddpmpp.py --mode train --workdir poisson_ddpmpp", the program keeps running, but there is no feedback from the terminal. I debugged the program and found that the program has been running in this line of code:

upfirdn2d_op = load(
    "upfirdn2d",
    sources=[
        os.path.join(module_path, "upfirdn2d.cpp"),
        os.path.join(module_path, "upfirdn2d_kernel.cu"),
    ],
)

Could you please tell me what I should do?

**Comment by reflectionie** [comment]
I checked the memory, nothing changed, but this line of code kept running without any feedback, I had to manually interrupt the run

**Comment by Newbeeer** [comment]
Hi,

I didn't encounter this issue before. I can do some research on it and get back to you. What's the gpu utilization when the program gets stuck?

Could you wait the program for a longer time, to see whether it will finish loading the files?

**Comment by reflectionie** [comment]
I waited for more than 20 minutes in this step, and kept checking the changes of GPU memory and memory, and there was no obvious change (18MiB/11264Mib), (this code is in "import run_lib", I think the training has not really started to execute yet?

**Comment by reflectionie** [comment]
I solved this problem, I found that there is a lock file in .cache/torch_extensions/; when i do rm -rf torch_extensions/* it solved the problem, thanks!
