### ISSUE TITLE
Hyper prarameters, l1 norm or l2 norm?

### ISSUE THREAD

**Issue by BEaN001** [Newbeeer/Poisson_flow#8]
Hi, I have a question which make me confused.
What is the 'Average norm of data' in hyper-parameters.py, l1 norm or l2 norm?  
I found that in the paper B1.1,  Ep(x)∣∣x∣∣^2 ≈ 900, ∣∣x∣∣ is the sign of l1 norm, but I caculated it with cifar10 train dataset(50000), the result is 28.9^2 when I use l2 norm.

**Comment by Newbeeer** [comment]
Hi,

The norm in our paper and code is $l_2$ norm. For example, the average $l_2$ norm on CIFAR-10 is approximately 33, and the corresponding the parameters for the script `hyper-parameters.py` on CIFAR-10 dataset are `--data_norm=33  --data_dim=3072`.

**Comment by liuyezhou** [comment]
Hi,  Could you please provide code of calculating average l2 norm on CIFAR-10?  Thanks!
